export { default as IconBack } from './arrow-back.svg';
export { default as IconHome } from './homebutton.svg';
export { default as IconBell } from './notificationbutton.svg';
export { default as IconMenu } from './historybutton.svg';
export { default as IconUser } from './profilebutton.svg';
export { default as Logo } from './logo.svg';
export { default as IconFoods } from './foods.svg';
export { default as IconDrinks } from './drinks.svg';
export { default as IconPastries } from './pastries.svg';